version: '3.9'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --standalone --non-interactive --agree-tos --email youremail@example.com -d vac-service.online --rsa-key-size 4096 --force-renewal || true"
    ports:
      - "8080:80"
    depends_on:
      - nginx
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - app
      
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  app:
    build: .
    image: ittadoru/saverbot:latest
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: >
      bash -c "uvicorn server:app --host 0.0.0.0 --port 8000 & python bot.py"

volumes:
  redis_data:
  certbot-etc: