version: '3.9'

services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    restart: always
    ports:
      - "8008:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  app:
    build: .
    image: ittadoru/saverbot:latest
    container_name: app
    restart: always
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      - redis
    command: >
      bash -c "uvicorn server:app --host 0.0.0.0 --port 8000 & python bot.py"

volumes:
  redis_data:
